#!/bin/sh
# Copyright 2011 Canonical, Inc
#           2014 Tianon Gravi
# Author: Serge Hallyn <serge.hallyn@canonical.com>
#         Tianon Gravi <tianon@debian.org>

# for simplicity this script provides no flexibility
USERS_TMP=""
for u in $UNPRIV_USERS
do
    id $u > /dev/null 2>&1
    if [ $? = 0 ]; then
	USERS_TMP="$USERS_TMP $u"
    fi
done
UNPRIV_USERS=$USERS_TMP

# if cgroup is mounted by fstab, don't run
# don't get too smart - bail on any uncommented entry with 'cgroup' in it
if grep -v '^#' /etc/fstab | grep -q cgroup; then
	echo 'cgroups mounted from fstab, not mounting /sys/fs/cgroup'
	exit 0
fi

# kernel provides cgroups?
if [ ! -e /proc/cgroups ]; then
	exit 0
fi

# if we don't even have the directory we need, something else must be wrong
if [ ! -d /sys/fs/cgroup ]; then
	exit 0
fi

# mount /sys/fs/cgroup if not already done
if ! mountpoint -q /sys/fs/cgroup; then
	mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
fi

cd /sys/fs/cgroup

# systemd cgroup
mkdir -p /sys/fs/cgroup/systemd/user.slice
mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
for u in $UNPRIV_USERS
do
	USER_CG="/sys/fs/cgroup/systemd/user.slice/user-$(id -u $u).slice"
	mkdir -p $USER_CG
	chown $(id -u $u):$(id -g $u) $USER_CG
	chown $(id -u $u):$(id -g $u) $USER_CG/{cgroup.procs,tasks}
done

# get/mount list of enabled cgroup controllers
for sys in $(awk '!/^#/ { if ($4 == 1) print $1 }' /proc/cgroups); do
	mkdir -p $sys
	if ! mountpoint -q $sys; then
		if ! mount -n -t cgroup -o $sys cgroup $sys; then
			rmdir $sys || true
		else
			echo 1 > /sys/fs/cgroup/$sys/cgroup.clone_children
			for u in $UNPRIV_USERS
			do
				USER_CG="$sys/user.slice/user-$(id -u $u).slice"
				mkdir -p $USER_CG
				chown $(id -u $u):$(id -g $u) $USER_CG
				chown $(id -u $u):$(id -g $u) $USER_CG/{cgroup.procs,tasks}
				echo 1 > $USER_CG/cgroup.clone_children
				if [ $sys = "cpuset" ]; then
					chown $(id -u $u):$(id -g $u) $USER_CG/cpuset.{cpus,mems}
					echo 0 > $USER_CG/cpuset.cpus
					echo 0 > $USER_CG/cpuset.mems
				fi
			done
		fi
	fi
done


# example /proc/cgroups:
#  #subsys_name	hierarchy	num_cgroups	enabled
#  cpuset	2	3	1
#  cpu	3	3	1
#  cpuacct	4	3	1
#  memory	5	3	0
#  devices	6	3	1
#  freezer	7	3	1
#  blkio	8	3	1

exit 0
